[workspace]
authors = ["Naren Prakash <146764727+narenp12@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "RRR-datacreation"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.2.4,<3"
pandas = ">=2.2.3,<3"
plotly = ">=6.0.1,<7"
scikit-learn = ">=1.6.1,<2"
ipykernel = ">=6.29.5,<7"

[pypi-dependencies]
paperscraper = ">=0.3.0, <0.4"
spacy = ">=3.8.5, <4"
